USE [master]
GO

/****** Object:  Database [MediaMgrSystem]    Script Date: 06/13/2014 16:08:19 ******/
CREATE DATABASE [MediaMgrSystem] ON  PRIMARY 
( NAME = N'MediaMgrSystem', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESSWEI\MSSQL\DATA\MediaMgrSystem.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MediaMgrSystem_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESSWEI\MSSQL\DATA\MediaMgrSystem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MediaMgrSystem] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MediaMgrSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MediaMgrSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MediaMgrSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MediaMgrSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MediaMgrSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MediaMgrSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MediaMgrSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MediaMgrSystem] SET  READ_WRITE 
GO

ALTER DATABASE [MediaMgrSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MediaMgrSystem] SET  MULTI_USER 
GO

ALTER DATABASE [MediaMgrSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MediaMgrSystem] SET DB_CHAINING OFF 
GO

