//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaMgrSystem {
    
    
    public partial class BroadcastMain {
        
        /// <summary>
        /// cList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MediaMgrSystem.ChannelList cList;
        
        /// <summary>
        /// EncoderList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MediaMgrSystem.VideoEncodeList EncoderList;
        
        /// <summary>
        /// audioEncoderList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MediaMgrSystem.AudioEncoderList audioEncoderList1;
    }
}
